# Generated by Django 2.2.2 on 2020-01-28 08:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, max_length=350, verbose_name='обо мне'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='media/icon-user-default.png', upload_to='media', verbose_name='автарка'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='создан в'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='ID (айди)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_members',
            field=models.ManyToManyField(blank=True, related_name='Subs', to=settings.AUTH_USER_MODEL, verbose_name='подписчики'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='емайл'),
        ),
    ]
