# Generated by Django 2.2.2 on 2020-03-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_is_coded'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusermodel',
            name='code_create_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
