# Generated by Django 2.2.2 on 2020-03-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_myusermodel_code_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusermodel',
            name='code_create_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
