# Generated by Django 2.2.2 on 2020-03-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200329_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusermodel',
            name='code_create_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Время создания'),
        ),
    ]
