# Generated by Django 2.2.2 on 2020-01-28 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='обновлен в')),
                ('lol', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('actions', models.BooleanField(default=False, verbose_name='Действия других пользователей')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='обновлен в')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='themes.Categories')),
            ],
            options={
                'verbose_name': 'Элемент темы',
                'verbose_name_plural': 'Элементы темы',
                'ordering': ['-created_at'],
            },
        ),
    ]
