# Generated by Django 2.2.2 on 2020-01-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='media/icon-user-default.png', upload_to='media', verbose_name='картинка'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='image',
            field=models.ImageField(default='media/icon-user-default.png', upload_to='media', verbose_name='картинка'),
        ),
    ]
