# Generated by Django 2.2.2 on 2020-01-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20200128_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='media/image-post-default.jpg', upload_to='media', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='image',
            field=models.ImageField(default='media/image-post-default.jpg', upload_to='media', verbose_name='картинка'),
        ),
    ]
