# Generated by Django 2.2.2 on 2020-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_auto_20200128_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='картинка'),
        ),
    ]
