# Generated by Django 2.2.2 on 2020-01-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_auto_20200128_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='картинка'),
        ),
    ]
