# Generated by Django 2.2.2 on 2020-03-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_auto_20200128_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='картинка'),
        ),
    ]
